const DARK_GRAY = '#222';
const LIGHT_GRAY = '#F3F3F3';
const MEDIUM_GRAY = '#797979';

export const COLORS = {
  white: '#fff',
  black: '#000',
  primary: '#1b6635',
  secondary: '#ffedbd',
  blue: '#007aff',
  mediumgray: MEDIUM_GRAY,
  borderGray: '#d8d8d8',
  danger: '#fb2625',
  lighttheme: {
    lightgray: '#F3F3F3',
    darkgray: '#222',
    background: LIGHT_GRAY,
    appBackground: '#ffedbd',
    text: '#000',
    buttonText: '#fff',
    buttonBackground: '#000',
    inputText: '#000',
    inputBackground: '#fff',
    inputBorderFocus: '#4fa2ee',
    numBtnBackground: '#c5c5c5',
    numText: '#5d5d5d',
    switchTrackActive: '#47673b',
    switchTrackInactive: '#cfcfcf',
    switchThumb: '#000',
  },
  darktheme: {
    lightgray: '#F3F3F3',
    darkgray: '#222',
    background: DARK_GRAY,
    appBackground: '#443f32',
    text: '#fff',
    buttonText: '#000',
    buttonBackground: '#fff',
    inputText: '#fff',
    inputBackground: '#000',
    inputBorderFocus: '#4fa2ee',
    numBtnBackground: '#5d5d5d',
    numText: '#c5c5c5',
    switchTrackActive: '#47673b',
    switchTrackInactive: '#cfcfcf',
    switchThumb: '#000',
  },
};
